package lab2;

import java.util.zip.*;
import java.awt.*;
import javax.swing.*;
import java.awt.Insets;
import java.awt.event.*;
import java.io.*;
import java.net.URL;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PEOPLE
 */
public class Toys extends javax.swing.JFrame {

    /**
     * Creates new form Toys
     */
    public Toys() {
        initComponents();
        addPaneListener();
        //////архів... розібратись
        currentDirectory = new File(".").getAbsolutePath().substring(0, new File(".").getAbsolutePath().length() - 2);
        ToysDataBase = currentDirectory + "\\files\\ToysDataBase\\";
        File TDB = new File(ToysDataBase + ".zip");
        if(!TDB.exists()) {
            try {
            TDB.createNewFile();
            FileOutputStream fout = new FileOutputStream(ToysDataBase + ".zip");
            ZipOutputStream zout = new ZipOutputStream(fout);
            ZipEntry ze = new ZipEntry("ToysDataBase1.txt");
            zout.putNextEntry(ze);
            zout.closeEntry();
            zout.close();
            ToysDataBase += "ToysDataBase1.txt";
            } catch (IOException ex){
                jLabel1.setText("Ffffse'");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jProgressBar1 = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Іграшки");
        setPreferredSize(new java.awt.Dimension(600, 400));

        jToolBar1.setAutoscrolls(true);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setDoubleBuffered(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(18, 30));
        jToolBar1.setMinimumSize(new java.awt.Dimension(18, 30));

        jToggleButton1.setText("Додати іграшку");
        jToggleButton1.setToolTipText("");
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        jToggleButton2.setText("Перегляд іграшок");
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton2);

        jToggleButton3.setText("Пошук іграшок");
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton3);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(5000, 5000));
        jDesktopPane1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5000, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.WEST);
        jDesktopPane1.getAccessibleContext().setAccessibleName("");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ready");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel1.add(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleName("jLabel1");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jSeparator1.setMaximumSize(new java.awt.Dimension(5, 20));
        jSeparator1.setMinimumSize(new java.awt.Dimension(5, 20));
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 20));
        jPanel1.add(jSeparator1);
        jPanel1.add(jProgressBar1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setComponent(JInternalFrame jfr, GridBagLayout gbl, GridBagConstraints gbc,
            Component c, int WIDTH, int HEIGHT, int row, int col, int nrow, int ncol) {
      c.setSize(WIDTH*10, HEIGHT*10);
      //c.setBackground(Color.cyan);
      gbc.anchor = GridBagConstraints.CENTER;
      gbc.fill = GridBagConstraints.BOTH;                      
      gbc.insets = new Insets(3, 3, 3, 3);
      gbc.gridx = col;
      gbc.gridy = row;
      gbc.gridwidth = ncol;
      gbc.gridheight = nrow;
      gbc.weightx = 0.1;
      gbc.weighty = 0.1;
      gbc.ipadx = 10;
      gbc.ipady = 6;
      gbl.setConstraints(c, gbc);
      jfr.add(c);
    }

    private static final int defaultNRow = 1;
    private static final int defaultNCol = 1;
    private String tempImage;
    JInternalFrame jfrAdd;
    JLabel labName;
    JTextField textName;
    JLabel labPrice;
    JTextField textPrice;
    JLabel labAge;
    JComboBox<AgeLimits> comboAge;
    JLabel labAttribute;
    JTextField textAttribute;
    JLabel labPicture;
    JButton butOK;   
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {
            if (jfrAdd != null) {
                jfrAdd.show();
            } else {              
                jfrAdd = new JInternalFrame("Додати іграшку");
                jfrAdd.setName("jfrAdd");
                jfrAdd.setResizable(true);
                jfrAdd.setClosable(true);
                GridBagLayout gbl = new GridBagLayout();
                GridBagConstraints gbc = new GridBagConstraints();
                jfrAdd.setLayout(gbl);                

                labName = new JLabel("Назва іграшки:");
                setComponent(jfrAdd, gbl, gbc, labName, 10, 2, 0, 0, defaultNRow, defaultNCol);

                textName = new JTextField(15);
                setComponent(jfrAdd, gbl, gbc, textName, 10, 2, 0, 1, defaultNRow, defaultNCol);

                labPrice = new JLabel("Ціна іграшки:");
                setComponent(jfrAdd, gbl, gbc, labPrice, 10, 2, 1, 0, defaultNRow, defaultNCol);

                textPrice = new JTextField(15);
                setComponent(jfrAdd, gbl, gbc, textPrice, 10, 2, 1, 1, defaultNRow, defaultNCol);

                labAge = new JLabel("Вікові межі:");
                setComponent(jfrAdd, gbl, gbc, labAge, 10, 2, 2, 0, defaultNRow, defaultNCol);

                AgeLimits[] defaultAgeLimits = new AgeLimits[] {
                  new AgeLimits(0, 3),
                  new AgeLimits(3, 5),
                  new AgeLimits(5, 8),
                  new AgeLimits(8, 8),
                  new AgeLimits(10, 10)
                };
                comboAge = new JComboBox<>(defaultAgeLimits);
                comboAge.setSize(1000, 3000);
                setComponent(jfrAdd, gbl, gbc, comboAge, 10, 2, 2, 1, defaultNRow, defaultNCol);

                labAttribute = new JLabel("Додаткова інф.:");
                setComponent(jfrAdd, gbl, gbc, labAttribute, 10, 2, 3, 0, defaultNRow + 1, defaultNCol);

                textAttribute = new JTextField(15);                
                setComponent(jfrAdd, gbl, gbc, textAttribute, 10, 2, 3, 1, defaultNRow + 1, defaultNCol);

                labPicture = new JLabel();
                labPicture.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                       try{
                       JFileChooser openImage = new JFileChooser();
                       openImage.showOpenDialog(jPanel1);
                       File imageFile = openImage.getSelectedFile();
                       
                       tempImage = imageFile.getAbsolutePath();
                       labPicture.setIcon(new ImageIcon(new ImageIcon(imageFile.getAbsolutePath()).getImage().getScaledInstance(labPicture.getWidth(),
                                labPicture.getHeight(), Image.SCALE_SMOOTH)));
                       
                       textName.setText(tempImage);
                       } catch(Exception ex){
                           labPicture.setIcon(new ImageIcon(new ImageIcon("images\\ico.jpg"
                        ,"Click to add new image.").getImage().getScaledInstance(labPicture.getWidth(),
                                labPicture.getHeight(), Image.SCALE_SMOOTH)));
                           tempImage = null;
                       }
                    }
                    
                    @Override
                    public void mousePressed(MouseEvent e) {
                        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }
                });
                labPicture.setBorder(new LineBorder(Color.cyan));
                setComponent(jfrAdd, gbl, gbc, labPicture, 15, 15, 0, 3, defaultNRow + 7, defaultNCol + 1);
                labPicture.setIcon(new ImageIcon(new ImageIcon("images\\ico.jpg"
                        ,"Click to add new image.").getImage().getScaledInstance(labPicture.getWidth(),
                                labPicture.getHeight(), Image.SCALE_SMOOTH)));
                
                butOK = new JButton("OK");
                butOK.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                    butOKActionPerformed(evt);
            }
        });
                setComponent(jfrAdd, gbl, gbc, butOK, 10, 2, 6, 1, defaultNRow, defaultNCol);

                jDesktopPane1.add(jfrAdd);
                Insets insets = jDesktopPane1.getInsets();
                jfrAdd.setPreferredSize(new Dimension(600, 250));
                Dimension size = jfrAdd.getPreferredSize();

                jfrAdd.setBounds(10 + insets.left, 10 + insets.top,
                        size.width, size.height);

                jfrAdd.setVisible(true);
            }
        } else {
            jfrAdd.hide();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void butOKActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            jLabel1.setText("Ready");
            double tmpPrice = Double.parseDouble(textPrice.getText());
            File sourceImage = new File(tempImage);
            String extension = sourceImage.getCanonicalPath().substring(sourceImage.getCanonicalPath().lastIndexOf("."));
            File destImage;
            String imageURL;
            do{
                int id = (int)(Math.random()*10 + Math.random()*100 + Math.random()*1000 + Math.random()*10000);
                imageURL = new File(".").getAbsolutePath() + "\\images\\" + id + extension;
                destImage = new File(imageURL);
            }
            while(destImage.exists());
            
            Files.copy(sourceImage.toPath(), destImage.toPath());
            Toy newToy = new Toy(textName.getText(), tmpPrice,
            (AgeLimits)comboAge.getSelectedItem(), textAttribute.getText(), imageURL);
            
            addToyToFile(newToy);
        } catch(Exception ex){
           jLabel1.setText("Error");
        }
    }
    
    
    JInternalFrame jfrView;
    JLabel labName1;
    JComboBox<Toy> comboName1;
    JLabel labPrice1;
    JLabel labAge1;
    JLabel labAttribute1;
    JLabel labPicture1;
    JButton butOK1;
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (jToggleButton2.isSelected()) {
            if (jfrView != null) {
                jfrView.show();
            } else {
                Toy toy = new Toy("name", 12.0d, new AgeLimits(0, 5), "bla bla bla", "ggg");//example
                Toy[] toyArray = new Toy[] {
                    toy
                };
                
                jfrView = new JInternalFrame("Перегляд всіх іграшок");
                jfrView.setName("jfrView");
                jfrView.setResizable(true);
                jfrView.setClosable(true);
                GridBagLayout gbl = new GridBagLayout();
                GridBagConstraints gbc = new GridBagConstraints();
                jfrView.setLayout(gbl);                

                ////////gridLayout
                /*
                int defWidth = 100;
                int defHeight = 20;
                
                 jfrView.setLayout(new GridLayout(3, 2, 5, 5));
                 
                 comboName1 = new JComboBox<>(toyArray);
                 comboName1.setSize(defWidth, defHeight);
                 jfrView.add(comboName1);
                 
                 labName1 = new JLabel("Назва іграшки: " + toy.getName());
                 
                 JLabel labName2 = new JLabel("Назва іграшки: " + toy.getName());
                 JLabel labName3 = new JLabel("Назва іграшки: " + toy.getName());
                 JLabel labName4 = new JLabel("Назва іграшки: " + toy.getName());
                 JRadioButton rb = new JRadioButton();
                 
                 //labName1.setSize(d);
                 jfrView.add(labName1);
                 jfrView.add(labName3);
                 jfrView.add(labName4);
                 jfrView.add(rb);
                 textAttribute = new JTextField(15);
                 
                 jfrView.add(textAttribute);
                 */
                //////////
                
                ////////////////////////////////////////////////////////////////
                comboName1 = new JComboBox<>(toyArray);
                setComponent(jfrView, gbl, gbc, comboName1, 10, 2, 0, 0, 1, 1);
                
                labName1 = new JLabel("Назва іграшки: " + toy.getName());
                setComponent(jfrView, gbl, gbc, labName1, 10, 2, 1, 0, 1, 1);

                labPrice1 = new JLabel("Ціна іграшки: " + toy.getPrice());
                setComponent(jfrView, gbl, gbc, labPrice1, 10, 2, 2, 0, defaultNRow, defaultNCol);

                labAge1 = new JLabel("Вікові межі: " + toy.getAgeLimits().toString());
                setComponent(jfrView, gbl, gbc, labAge1, 10, 2, 3, 0, defaultNRow, defaultNCol);

                labAttribute1 = new JLabel("Додаткова інф.: " + toy.getAttribute());
                setComponent(jfrView, gbl, gbc, labAttribute1, 10, 2, 4, 0, defaultNRow + 1, defaultNCol);

                labPicture1 = new JLabel();
                labPicture1.setBorder(new LineBorder(Color.cyan));
                setComponent(jfrView, gbl, gbc, labPicture1, 15, 15, 0, 1, defaultNRow + 6, 2);
                labPicture1.setIcon(new ImageIcon(new ImageIcon(toy.getPictureURL()
                        ,"Not found").getImage().getScaledInstance(labPicture1.getWidth(),
                                labPicture1.getHeight(), Image.SCALE_DEFAULT)));
                
                butOK1 = new JButton("OK");
                setComponent(jfrView, gbl, gbc, butOK1, 10, 2, 6, 0, defaultNRow, 2);
             
                Insets insets = jDesktopPane1.getInsets();
                jfrView.setPreferredSize(new Dimension(600, 250));
                Dimension size = jfrView.getPreferredSize();

                jfrView.setBounds(30 + insets.left, 10 + insets.top,
                        size.width, size.height);
                
                jfrView.pack();
                jfrView.setVisible(true);
                jDesktopPane1.add(jfrView);
            }
        } else {
            jfrView.hide();
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    JInternalFrame jfrSearch;
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        if (jToggleButton3.isSelected()) {
            if (jfrSearch != null) {
                jfrSearch.show();
            } else {
                jfrSearch = new jfrSearch("Пошук за критеріями");//new JInternalFrame("Пошук за критеріями");
                jfrSearch.setName("jfrSearch");
                //jfrSearch.setResizable(true);
                jfrSearch.setClosable(true);
                
                Insets insets = jDesktopPane1.getInsets();
                //jfrView.setPreferredSize(new Dimension(600, 250));
                Dimension size = jfrSearch.getPreferredSize();

                jfrSearch.setBounds(50 + insets.left, 10 + insets.top,
                        size.width, size.height);
                
                jfrSearch.pack();
                jfrSearch.setVisible(true);
                jDesktopPane1.add(jfrSearch);
            }
        } else {
            jfrSearch.hide();
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Toys mainFrame = new Toys();
                mainFrame.setVisible(true);
                mainFrame.setExtendedState(MAXIMIZED_BOTH);

                ImageIcon icon = new ImageIcon("images/ico.jpg");
                mainFrame.setIconImage(icon.getImage());
            }
        });
    }

    public void addPaneListener() {
        jDesktopPane1.addContainerListener(new ContainerAdapter() {
            public void componentRemoved(ContainerEvent e) {
                String tmp = e.getChild().getName();
                if (tmp.equals("jfrAdd")) {
                    jfrAdd = null;
                    jToggleButton1.setSelected(false);
                } else if(tmp.equals("jfrView")) {
                    jfrView = null;
                    jToggleButton2.setSelected(false);
                } else if(tmp.equals("jfrSearch")) {
                    jfrSearch = null;
                    jToggleButton3.setSelected(false);
                };
            };
        });
    }
    
    private void addToyToFile(Toy toy) {        
        try{
            
            jLabel1.setText("Added");
        } catch(Exception ex) {
            jLabel1.setText("Error");
        }
    }

    private String currentDirectory;
    private String ToysDataBase;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
